name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build --base-href /portfolio
      
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist/portfolio/browser
        GITHUB_TOKEN: ${{ secrets.PORTFOLIO_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"
