name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      
    - name: Copy build to another branch
      run: |
        git config --global user.email "kulinasmindaugas@gmail.com"
        git config --global user.name "Mindaugas Kulinas"
        git checkout -b built-project
        git add dist/ -f
        git commit -m "Built project from main branch"
        git push origin built-project
